version: "3"
services:
  #ちなみにnodeはphp-fpm内にnodeを入れる
  php-fpm:
    container_name: lara_nux_php
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./laravel/:/var/www/html/
    networks:
      - lara_nux
  nginx:
    container_name: lara_nux_nginx
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - ./laravel/:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lara_nux

  node:
    container_name: lara_nux_node
    build:
        context: "./docker/node"
        dockerfile: "Dockerfile"
    volumes:
        - ./nuxt/:/var/www/html
    tty: true
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true    
    ports:
        - "3000:3000"
    networks:
      - lara_nux
  db:
    container_name: lara_nux_db
    build:
      context: "./docker/postgres"
      dockerfile: "Dockerfile"
    depends_on:
      - php-fpm
    ports:
      - 5432:5432
    #volumes:
    # もし永続化させたいときにはこの部分を記載
    #  - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lara_nux
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - lara_nux
      
  localstack:
    image: localstack/localstack
    container_name: lara_nux_s3
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./docker/localstack/data:/tmp/localstack/data
    networks:
      - lara_nux
networks:
  lara_nux:
    driver: "bridge"